# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wt < Formula
  desc "Manage isolated git worktrees for parallel Claude Code sessions"
  homepage "https://github.com/emilrex/wt"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/EmilRex/wt/releases/download/v0.1.2/wt_0.1.2_darwin_amd64.tar.gz"
      sha256 "7fa9dedae1777a09ea4e2b200e590664c3681f210c3501c31059d8354aa94531"

      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/EmilRex/wt/releases/download/v0.1.2/wt_0.1.2_darwin_arm64.tar.gz"
      sha256 "d6e3ffa2d34744d5a93e2665ad291383c889a45c06a5bfc67be8e82462a0c617"

      def install
        bin.install "wt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/EmilRex/wt/releases/download/v0.1.2/wt_0.1.2_linux_amd64.tar.gz"
      sha256 "e679523d6f4b5883b9c27c0eac159e5446ad9c3118202b605a343806ec1cf496"
      def install
        bin.install "wt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/EmilRex/wt/releases/download/v0.1.2/wt_0.1.2_linux_arm64.tar.gz"
      sha256 "a34fc62ef1c3e1018ec6dc345c73096c1aa5bdfd2f10f4ee7272794ef235d7f2"
      def install
        bin.install "wt"
      end
    end
  end
end
