# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Manage isolated git worktrees for parallel Claude Code sessions"
  homepage "https://github.com/emilrex/wt"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "5b8af48965b2a28958e3ef5520062e13fc187ad7b9cb5a35888445f839173ab2"
    end
    on_arm do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "117d1e73c3ad450bb521ac97b38689bbc4d781a6e667f35467104bdfccfb8879"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "6ec32f66a1f1dd3bfce46776c6483c88fade97a7d5852e06c9b80a92a3696049"
    end
    on_arm do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "265a3a056dcc12b109ede25c8f3d082c7d0ddcdc1a16f1c7438722def3cf8e18"
    end
  end

  # No zap stanza required
end
