# This file was generated by GoReleaser. DO NOT EDIT.
cask "wt" do
  name "wt"
  desc "Manage isolated git worktrees for parallel Claude Code sessions"
  homepage "https://github.com/emilrex/wt"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "wt"

  on_macos do
    on_intel do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_darwin_amd64.tar.gz"
      sha256 "60b78e96c37825e31572e80373e03ae80eba6999710e3911e1ad329ea1c360cb"
    end
    on_arm do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_darwin_arm64.tar.gz"
      sha256 "efd67a5e5efe92d145a888ec71d6d47070be2524fd1830013a382d4940860198"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_linux_amd64.tar.gz"
      sha256 "90f8b7be16771364143f9c1c6bbd1faff17caf869f42ef19fb82344754170554"
    end
    on_arm do
      url "https://github.com/EmilRex/wt/releases/download/v#{version}/wt_#{version}_linux_arm64.tar.gz"
      sha256 "1a62cb227f59183a2cb229d4972bfa754f81d32166782f3294129cefdda7612c"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/wt"]
  end

  # No zap stanza required
end
